-- ENABLE THE EXTENSION FIRST
CREATE EXTENSION IF NOT EXISTS vector;

DROP TABLE IF EXISTS book_authors CASCADE;
DROP TABLE IF EXISTS book_categories CASCADE;
DROP TABLE IF EXISTS book_embeddings CASCADE;
DROP TABLE IF EXISTS books CASCADE;
DROP TABLE IF EXISTS authors CASCADE;
-- Then re-run your CREATE TABLE script

-- 1. Create the base tables with Identity columns
CREATE TABLE books (
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    title TEXT NOT NULL,
    publisher TEXT,
    published_date TEXT,
    description TEXT,
    page_count INTEGER,
    print_type TEXT,
    language TEXT,
    info_link TEXT,
    small_thumbnail TEXT,
    isbn TEXT UNIQUE
);

CREATE TABLE authors (
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    name TEXT UNIQUE NOT NULL,
    birth_date DATE,   -- Changed to DATE
    death_date DATE,   -- Changed to DATE
    nationality TEXT,
    sex TEXT,
    bio TEXT,
    author_link TEXT
);

CREATE TABLE categories (
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    name TEXT UNIQUE NOT NULL
);

-- 2. Update Relationship tables to use INTEGER foreign keys
CREATE TABLE book_authors (
    book_id INTEGER REFERENCES books(id) ON DELETE CASCADE,
    author_id INTEGER REFERENCES authors(id) ON DELETE CASCADE,
    PRIMARY KEY (book_id, author_id)
);

CREATE TABLE book_categories (
    book_id INTEGER REFERENCES books(id) ON DELETE CASCADE,
    category_id INTEGER REFERENCES categories(id) ON DELETE CASCADE,
    PRIMARY KEY (book_id, category_id)
);

-- 3. Update Embedding tables
CREATE TABLE book_embeddings (
    book_id INTEGER REFERENCES books(id) ON DELETE CASCADE,
    model_name TEXT,
    vector VECTOR(1536), 
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (book_id, model_name)
);

CREATE TABLE author_embeddings (
    author_id INTEGER REFERENCES authors(id) ON DELETE CASCADE,
    model_name TEXT,
    vector VECTOR(1536), 
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (author_id, model_name)
);

-- Create HNSW index for fast Cosine Similarity searches
CREATE INDEX ON book_embeddings 
USING hnsw (vector vector_cosine_ops);

CREATE INDEX ON author_embeddings 
USING hnsw (vector vector_cosine_ops);